# Generated by Django 4.1.4 on 2022-12-26 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesOrderHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ammend_no', models.CharField(blank=True, max_length=50, null=True)),
                ('sales_order_no', models.CharField(default='PO-00000001', max_length=50)),
                ('sales_order_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.IntegerField(default=1)),
                ('deleted', models.BooleanField(default=0)),
                ('salesperson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='front.salesperson')),
            ],
            options={
                'verbose_name_plural': 'sales_order_header',
                'db_table': 'sales_order_header',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SalesOrderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ammend_no', models.CharField(blank=True, max_length=50, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('delivered_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('deleted', models.BooleanField(default=0)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SalesItem', to='front.itemmaster')),
                ('sales_order_header', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='front.salesorderheader')),
            ],
            options={
                'verbose_name_plural': 'sales_order_details',
                'db_table': 'sales_order_details',
                'managed': True,
            },
        ),
    ]
