# Generated by Django 4.1.4 on 2022-12-13 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pswd_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
