# Generated by Django 4.1.4 on 2023-01-03 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesperson',
            name='gst_no',
        ),
    ]
