# Generated by Django 4.1.4 on 2022-12-21 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorderheader',
            name='status',
            field=models.SmallIntegerField(default=1),
        ),
    ]
