# Generated by Django 4.1.4 on 2022-12-21 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0002_alter_purchaseorderheader_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnTransitHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_number', models.CharField(blank=True, max_length=15, null=True)),
                ('transfer_date', models.DateField(blank=True, null=True)),
                ('deleted', models.BooleanField(default=0)),
                ('store_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='TransitFromStore', to='front.storemaster')),
                ('store_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='TransitToStore', to='front.storemaster')),
            ],
            options={
                'verbose_name_plural': 'on_transit_header',
                'db_table': 'on_transit_header',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OnTransitDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deleted', models.BooleanField(default=0)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='TransitItem', to='front.itemmaster')),
                ('on_transit_header', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='front.ontransitheader')),
            ],
            options={
                'verbose_name_plural': 'on_transit_details',
                'db_table': 'on_transit_details',
                'managed': True,
            },
        ),
    ]
