# Generated by Django 4.1.4 on 2022-12-13 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0002_user_pswd_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
