# Generated by Django 4.1.4 on 2022-12-19 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0002_remove_purchaseorderheader_store'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('deleted', models.BooleanField(default=0)),
            ],
            options={
                'verbose_name_plural': 'transaction_types',
                'db_table': 'transaction_types',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='StoreTransactionHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_number', models.CharField(blank=True, max_length=15, null=True)),
                ('transaction_date', models.DateField(blank=True, null=True)),
                ('reference_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='front.purchaseorderheader')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='front.storemaster')),
                ('transaction_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='front.transactiontype')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='front.vendormaster')),
            ],
            options={
                'verbose_name_plural': 'store_transaction_header',
                'db_table': 'store_transaction_header',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='StoreTransactionDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.SmallIntegerField(blank=True, default=1, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('deleted', models.BooleanField(default=0)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='StoreItem', to='front.itemmaster')),
                ('store_transaction_header', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='front.storetransactionheader')),
            ],
            options={
                'verbose_name_plural': 'store_transaction_details',
                'db_table': 'store_transaction_details',
                'managed': True,
            },
        ),
    ]
