# Generated by Django 4.1.4 on 2023-01-05 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0002_remove_salesperson_gst_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceheader',
            name='invoice_type',
            field=models.SmallIntegerField(default=1),
        ),
    ]
