# Generated by Django 4.1.4 on 2022-12-19 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0003_transactiontype_storetransactionheader_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storetransactionheader',
            old_name='reference_number',
            new_name='purchase_order_header',
        ),
        migrations.AddField(
            model_name='storetransactionheader',
            name='deleted',
            field=models.BooleanField(default=0),
        ),
    ]
