# Generated by Django 4.1.4 on 2022-12-21 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0003_ontransitheader_ontransitdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='ontransitheader',
            name='status',
            field=models.SmallIntegerField(default=1),
        ),
    ]
