# Generated by Django 4.1.4 on 2022-12-27 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0003_rename_term_id_invoiceterms_term'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoicePayments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.SmallIntegerField(default=1)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='front.customer')),
                ('invoice_header', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='front.invoiceheader')),
            ],
            options={
                'verbose_name_plural': 'invoice_payments',
                'db_table': 'invoice_payments',
                'managed': True,
            },
        ),
    ]
