# Generated by Django 4.1.4 on 2022-12-14 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0004_remove_user_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='deleted',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='storemaster',
            name='deleted',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='vendormaster',
            name='deleted',
            field=models.BooleanField(default=0),
        ),
    ]
