# Generated by Django 4.1.4 on 2022-12-20 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0004_rename_reference_number_storetransactionheader_purchase_order_header_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storetransactionheader',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
