# Generated by Django 4.1.4 on 2022-12-27 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0004_invoicepayments'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceheader',
            name='carrying_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
