# Generated by Django 4.1.4 on 2022-12-14 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0005_customer_deleted_storemaster_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemctegory',
            name='deleted',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='itemmaster',
            name='deleted',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='plydimensionmaster',
            name='deleted',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='purchaseorderdetails',
            name='deleted',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='purchaseorderheader',
            name='deleted',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='purchaseorderterms',
            name='deleted',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='standardtermmaster',
            name='deleted',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='storeitemmaster',
            name='deleted',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='uommaster',
            name='deleted',
            field=models.BooleanField(default=0),
        ),
    ]
