# Generated by Django 4.1.4 on 2022-12-20 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0005_storetransactionheader_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storetransactiondetails',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='front.transactiontype'),
        ),
    ]
