# Generated by Django 4.1.4 on 2022-12-22 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0005_ontransitdetails_delivered_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='ontransitdetails',
            name='delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
