# Generated by Django 4.1.4 on 2022-12-22 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0006_ontransitdetails_delivery_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='storetransactionheader',
            name='on_transit_header',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='front.ontransitheader'),
        ),
    ]
