# Generated by Django 4.1.4 on 2023-01-10 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0007_remove_vendordetails_vendor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesorderheader',
            name='commission',
        ),
    ]
