# Generated by Django 4.1.4 on 2022-12-22 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0007_storetransactionheader_on_transit_header'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storetransactiondetails',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='storetransactiondetails',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
