# Generated by Django 4.1.4 on 2022-12-27 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0007_salesorderheader_commission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorderheader',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='front.customer'),
        ),
    ]
