# Generated by Django 4.1.4 on 2023-01-10 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0008_remove_salesorderheader_commission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverychallanheader',
            name='invoice_header',
        ),
        migrations.AlterField(
            model_name='deliverychallanheader',
            name='delivery_challan_number',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='deliverychallanheader',
            name='sales_order_header',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='front.salesorderheader'),
        ),
        migrations.AlterField(
            model_name='ontransitheader',
            name='transfer_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorderheader',
            name='purchase_order_no',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='salesorderheader',
            name='sales_order_no',
            field=models.CharField(max_length=15),
        ),
    ]
