# Generated by Django 4.1.4 on 2022-12-28 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0008_salesorderheader_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemAttributes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(blank=True, max_length=30, null=True)),
                ('value', models.TextField(blank=True, null=True)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='front.itemmaster')),
            ],
            options={
                'verbose_name_plural': 'item_attributes',
                'db_table': 'item_attributes',
                'managed': True,
            },
        ),
    ]
