# Generated by Django 4.1.4 on 2023-01-10 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0009_remove_deliverychallanheader_invoice_header_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transportheader',
            options={'managed': True, 'verbose_name_plural': 'transport_header'},
        ),
        migrations.AlterModelTable(
            name='transportheader',
            table='transport_header',
        ),
    ]
