# Generated by Django 4.1.4 on 2022-12-28 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0009_itemattributes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemattributes',
            old_name='field',
            new_name='attribute_name',
        ),
        migrations.RenameField(
            model_name='itemattributes',
            old_name='value',
            new_name='attribute_value',
        ),
    ]
