# Generated by Django 4.1.4 on 2023-01-10 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0010_alter_transportheader_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceheader',
            name='vehicle_number',
        ),
    ]
