# Generated by Django 4.1.4 on 2022-12-30 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0011_paymentmethods_invoicepayments_reference_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicepayments',
            name='carrying_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='invoicepayments',
            name='due_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='invoicepayments',
            name='gst_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
