# Generated by Django 4.1.4 on 2022-12-22 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0011_physicalstockdetails_original_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='physicalstockdetails',
            name='status',
            field=models.SmallIntegerField(default=1),
        ),
    ]
