# Generated by Django 4.1.4 on 2022-12-30 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0012_invoicepayments_carrying_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicepayments',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
