# Generated by Django 4.1.4 on 2022-12-22 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0013_remove_physicalstockdetails_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='storetransactiondetails',
            name='on_transit_header',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='front.ontransitheader'),
        ),
        migrations.AddField(
            model_name='storetransactiondetails',
            name='physical_stock_header',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='front.physicalstockheader'),
        ),
        migrations.AddField(
            model_name='storetransactiondetails',
            name='purchase_order_header',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='front.purchaseorderheader'),
        ),
    ]
