# Generated by Django 4.1.4 on 2022-12-30 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0014_invoiceheader_due_amount_invoiceheader_total_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceheader',
            name='due_amount',
        ),
        migrations.RemoveField(
            model_name='invoiceheader',
            name='total_amount',
        ),
    ]
