# Generated by Django 4.1.4 on 2022-12-22 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0014_storetransactiondetails_on_transit_header_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storetransactiondetails',
            name='on_transit_header',
        ),
        migrations.RemoveField(
            model_name='storetransactiondetails',
            name='physical_stock_header',
        ),
        migrations.RemoveField(
            model_name='storetransactiondetails',
            name='purchase_order_header',
        ),
        migrations.AddField(
            model_name='physicalstockdetails',
            name='status',
            field=models.SmallIntegerField(default=1),
        ),
    ]
