# Generated by Django 4.1.4 on 2022-12-22 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0015_remove_storetransactiondetails_on_transit_header_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='physicalstockdetails',
            name='status',
        ),
    ]
