# Generated by Django 4.1.4 on 2022-12-30 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0015_remove_invoiceheader_due_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceheader',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
