# Generated by Django 4.1.4 on 2022-12-23 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0016_remove_physicalstockdetails_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='existing_invoice_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
