# Generated by Django 4.1.4 on 2022-12-30 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0016_invoiceheader_paid_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceheader',
            name='due_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='invoiceheader',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
