# Generated by Django 4.1.4 on 2022-12-23 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0017_customer_existing_invoice_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(blank=True, max_length=15, null=True)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('invoice_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('invoice_gst_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.SmallIntegerField(default=1)),
                ('deleted', models.BooleanField(default=0)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='InvoiceCustomer', to='front.customer')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='InvoiceStore', to='front.storemaster')),
            ],
            options={
                'verbose_name_plural': 'invoice_header',
                'db_table': 'invoice_header',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='InvoiceDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('invoice_item_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('invoice_item_gst_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('deleted', models.BooleanField(default=0)),
                ('invoice_header', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='front.invoiceheader')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='InvoiceItem', to='front.itemmaster')),
            ],
            options={
                'verbose_name_plural': 'invoice_details',
                'db_table': 'invoice_details',
                'managed': True,
            },
        ),
    ]
