# Generated by Django 4.1.4 on 2022-12-24 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0019_storetransactionheader_invoice_header'),
    ]

    operations = [
        migrations.AddField(
            model_name='storetransactionheader',
            name='total_gst_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
