# Generated by Django 4.1.4 on 2022-12-24 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0020_storetransactionheader_total_gst_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='storetransactiondetails',
            name='gst_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='storetransactiondetails',
            name='gst_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
