# Generated by Django 4.1.4 on 2022-12-24 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0021_storetransactiondetails_gst_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceheader',
            name='vehicle_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
